spring: 
   profiles: 
      active: 
          dev
---
spring: 
    profiles: dev
    application: 
          name: m-c-dev
---
spring: 
    profiles: test
    application: 
          name: m-c-test 